# Generated by Django 4.2.4 on 2023-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ct_brake",
            new_name="C_T_brake",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ct_brake_type",
            new_name="C_T_brake_type",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ct_gear_box",
            new_name="C_T_gear_box",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ct_motor",
            new_name="C_T_motor",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ct_motor_rpm",
            new_name="C_T_motor_rpm",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ct_speed",
            new_name="C_T_speed",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ct_wheel",
            new_name="C_T_wheel",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ct_wheel_type",
            new_name="C_T_wheel_type",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ct_wheel_type2",
            new_name="C_T_wheel_type_2",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="po_date",
            new_name="P_O_Date",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="ponumber",
            new_name="P_O_Number",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="wonumber",
            new_name="Work_Order_Number",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes1",
            new_name="notes_1",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes10",
            new_name="notes_10",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes2",
            new_name="notes_2",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes3",
            new_name="notes_3",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes4",
            new_name="notes_4",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes5",
            new_name="notes_5",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes6",
            new_name="notes_6",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes7",
            new_name="notes_7",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes8",
            new_name="notes_8",
        ),
        migrations.RenameField(
            model_name="hoistworkorder",
            old_name="notes9",
            new_name="notes_9",
        ),
        migrations.RemoveField(
            model_name="hoistworkorder",
            name="ct_creep",
        ),
        migrations.RemoveField(
            model_name="hoistworkorder",
            name="ct_limit_switch",
        ),
        migrations.RemoveField(
            model_name="hoistworkorder",
            name="lt_creep",
        ),
        migrations.RemoveField(
            model_name="hoistworkorder",
            name="lt_limit_switch",
        ),
        migrations.AddField(
            model_name="hoistworkorder",
            name="C_T_creep",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hoistworkorder",
            name="C_T_limit_switch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "0"),
                    ("Required", "Required"),
                    ("Not Required", "Not Required"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hoistworkorder",
            name="L_T_creep",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hoistworkorder",
            name="L_T_limit_switch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "0"),
                    ("Required", "Required"),
                    ("Not Required", "Not Required"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hoistworkorder",
            name="gravity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "0"),
                    ("Required", "Required"),
                    ("Not Required", "Not Required"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hoistworkorder",
            name="hoist_creep",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
