# Generated by Django 4.2.4 on 2023-08-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0002_rename_ct_brake_hoistworkorder_c_t_brake_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hoistworkorder",
            name="notes_10",
        ),
        migrations.RemoveField(
            model_name="hoistworkorder",
            name="notes_9",
        ),
    ]
