# Generated by Django 4.2.4 on 2023-08-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infosheet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoistinformationsheet",
            name="date_of_test",
            field=models.DateField(blank=True, null=True),
        ),
    ]
