# Generated by Django 4.2.4 on 2023-08-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infosheet", "0002_hoistinformationsheet_date_of_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoistinformationsheet",
            name="proof_of_load_applied",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
